# Title of the page
title: "Timeline of Simon"
# Your name
author: Simon Nußbaumer
# Show a link to LinkedIn in the header intro. Comment out to disable.
linkedin: https://www.linkedin.com/in/ponjimon/
# Show a link at the top of your timeline to your main personal site
# Comment this out to disable
personal_site:
  url: https://simon.events
  title: simon.events
# show today marker at end of timeline
show_today: false

# Your timeline is split into periods (e.g., decades, childhood/teens/adult, "Before Timeliner"/"After Timeliner", etc)
# Each period has a list of events formatted as `- date: title`. If you don't want to have period dividers, leave out the name field.
periods:
  - name: Experience
    events:
    - May 2016: "Started working at a Software Engineer at Hitbox Entertainment GmbH"
    - April 2016: "Left job as an IT technician at Triware IT GmbH"
    - January 2016: "Started working as an IT technician at Triware IT GmbH"
    - May 2014: "Finished civil service at Lebenshilfe Vorarlberg"
    - September 2013: "Started civil service at Lebenshilfe Vorarlberg"
  - name: Education
    events:
    - 2015: "Quit studying Computer Science at University of Vienna"
    - 2014: "Started studying Computer Science at University of Vienna"
    - 2013: "Graduated from BORG Dornbirn-Schoren"
    - 2008: "Joined BORG Dornbirn-Schoren with focus on informatics"
    - 2004: "Joined BRG Dornbirn-Schoren"
